### ISSUE TITLE
Some errors I received on Ubuntu 16.04 when installing dependencies

### ISSUE THREAD

**Issue by Simplexletalis** [kayabaNerve/tip-bot#1]
make[1]: Leaving directory '/root/tip-bot/node_modules/sodium/build'
npm ERR! Linux 4.4.0-98-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v4.8.6
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package erlpack@0.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer discord.js@11.2.1 wants erlpack@hammerandchisel/erlpack

npm ERR! Please include the following file with any support request:
npm ERR!     /root/tip-bot/npm-debug.log

**Comment by Kevin43** [comment]
Same issue on 14.04

**Comment by kayabaNerve** [comment]
Apparently I forgot to watch this repository. These comments are months old. Sorry for never responding.

discord.js requests 5 other NPM packages also be installed, and throws errors, yet those packages are optional (for voice chat IIRC). If you can ignore those errors and the bot still runs, do it.

This bug appears to be the result of Discord renaming from Hammer And Chisel and fixed in discord.js updates.

https://github.com/discordjs/discord.js/issues/2141
